language: node_js
git:
  submodules: false
node_js:
  - "0.10"
before_install:
  - git submodule update --init lib/
  - npm install -g bower phantomjs casperjs
  - npm install
  - bower install
before_script:
  - phantomjs --version
  - casperjs --version
script:
  - npm run travis
